test: fix a test error when the build for firefox doesn't exist
Error: Jest: Got error running globalSetup - .../EdgeTranslate/test/e2e/jest/global-setup.js, reason: File not found: build/firefox